### ISSUE TITLE
Return more convenient json from micro-controller

### ISSUE THREAD

**Issue by nemoipaha** [GienekGenin/SolarControl#16]
https://github.com/GienekGenin/SolarControl/blob/66e2eb3effe465f4e26af5b5fcbb57394112be45/MEAN-NodeMCU/server/server.js#L54

Would be nice to separate json response into 2 objects, one for light sensor and second for another sensor.
Smth like 

`{ data: { light: { l1: ..., l2: ... }, temperature: { t1: ..., t2: ... } }`

**Comment by GienekGenin** [comment]
Done
